### ISSUE TITLE
Deprecated API

### ISSUE THREAD

**Issue by tomsun3** [doorbell/ios-sdk#19]
Hi! Just to let you know:

`[[UIApplication sharedApplication] openURL:doorbellURL];`

XCode complains, at the line above:

`'openURL:' is deprecated: first deprecated in iOS 10.0`

**Comment by manavo** [comment]
Hey @tomsun3, thanks for the report!

This is already handled, although I don't think there's anything we can do about the warning: https://github.com/doorbell/ios-sdk/blob/master/Classes/DoorbellDialog.m#L136

It is just a warning you're getting, right? Or is it actually failing to run?

**Comment by tomsun3** [comment]
Hi @manavo !

Oh, I'm sorry, I did not see the if and version check... Of course, it's only a warning - no big deal!

To be honest, I'm not sure, what could be done. Maybe raising the minimum iOS version for the library, as 10.0 is already pretty old....

But yeah, just a warning.. Thank you!

**Comment by manavo** [comment]
Hey @tomsun3, I did try and bump the version a little while back, but people still needed older iOS version supported (back to 9), which lead to #16

Might be able to look at this again since it's been a little while since then, and maybe I don't need to bump it as far up as 13. I guess iOS 9 came out over 6 years ago, so not unreasonable to drop support for it!

**Comment by tomsun3** [comment]
I understand. It's not easy to find the golden mean. Thanks.

**Comment by manavo** [comment]
I'll close this for now, but will look into bumping the minimum iOS version so we can at least avoid the unnecessary warnings!
